# Site Settings
title:               Gabriel Martinez
tagline:             a blog
description:
baseurl:            ""
url:                "http://gabemartinez.github.io"
github:
  url:               "http://gabemartinez.github.io"
author:
  name:              "Gabriel Martinez"
  email:             "hi@martinezgabriel.com"
  twitter:           "gabrielmartinez"
  instagram:         #""
  github:            "gabemartinez"
  facebook:          #""
  linkedin:          "martinezg"
navigation:
- title: About
  url: /about
- title: Contact
  url: /contact
- title: Archive
  url: /archive  

paginate:            4
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
